### ISSUE TITLE
Consider merging pull requests via rebase

### ISSUE THREAD

**Issue by lpil** [alpaca-lang/alpaca_lib#11]
Hello!

GitHub fairly recently added the ability to merge in pull requests via rebase. Would you consider using this method instead of a merge commit? I find the history free of branching and merge commits easier to read :)

Cheers,
Louis

**Comment by tsloughter** [comment]
+1 rebase or squash with merge turned off in the github settings is what I prefer.

**Comment by j14159** [comment]
Works for me, rebase is now the default.
